name: KInvBackup
main: com.gmail.kamilkime.KInvBackup
version: 1.0
author: Kamilkime
commands:
  kinv:
    aliases: [kinvbackup, kbackup, kib]
permissions:
  kinv.*:
    default: true
    children:
      kinv.backup: true
      kinv.reload: true
      kinv.restore: true
      kinv.show: true